#!/bin/bash

INSTRUMENTATIONKEY=$(awk '$1=="INSTRUMENTATIONKEY"{print $2}' ~/.appinsightsrc)
LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY=$(awk '$1=="LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY"{print $2}' ~/.appinsightsrc) 

docker run -e APPINSIGHTS_INSTRUMENTATIONKEY=$INSTRUMENTATIONKEY -e APPINSIGHTS_LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY=$LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY -it -p 55678:55678 daprio/dapr-localforwarder:latest
